id: sender1
type: sender
emulator_id: emulator1
network:
  listen_port: 50800
  bind_address: "0.0.0.0"
  connect_to:
    - host: "localhost"
      port: 50804
sender_config:
  data_format: "raw"
  chunk_size: "1M"
  test_data:
    size: "100M"
    pattern: "random" 