#!/bin/bash

if [ -e $1.cc ]
then
    g++ -DNO_MAKEFILE -fpermissive -floop-parallelize-all -ffinite-math-only -floop-strip-mine \
        -fmove-loop-invariants  -std=c++17 -O3 $1.cc -o $1 -lm -lpthread
    
    # Check if compilation was successful
    if [ $? -eq 0 ]; then
        echo "Build successful: $1"
    else
        echo "Build failed. See error messages above."
        exit 1
    fi
else
    echo "No such file $1.cc"
    exit 1
fi
# for f in *cc; do ./buildp $(basename $f .cc); done
