---
io-services:
  reader:
    class: org.jlab.ersap.actor.pcap.services.PcapSourceEngine
    name: pcap-source
  writer:
    class: org.jlab.ersap.actor.pcap.services.PcapSinkEngine
    name: pcap-sink

services:
  - class: org.jlab.ersap.actor.pcap.services.PcapProcessorEngine
    name: pcap-processor

mime-types:
  - binary/pcap-event

# Container configuration
container:
  name: pcap
  type: java
  pools:
    - name: default
      size: 2
    - name: processor
      size: 4

# Service deployment
services-map:
  - name: pcap-source
    container: pcap
    pool: default
  - name: pcap-processor
    container: pcap
    pool: processor
  - name: pcap-sink
    container: pcap
    pool: default

configuration:
  io-services:
    reader:
      config_file: /workspace/src/utilities/java/pcap2streams/custom-config/ip-based-config.json
      streamHost: "localhost"
      streamPort: 7777
      ringBufferSize: 1024
      connectionTimeout: 5000
      readTimeout: 2000
      debug: true
    writer:
      output_dir: /workspace/src/utilities/java/pcap-ersap/output
      debug: true
  
  services:
    pcap-processor:
      protocol_filter: ""
      ip_filter: ""
      debug: true

global:
  threads: 4
  log-level: FINEST 