---
io-services:
  reader:
    class: org.jlab.ersap.actor.pcap.engine.PcapSourceEngine
    name: Source
  writer:
    class: org.jlab.ersap.actor.pcap.engine.PcapSinkEngine
    name: Sink
services:
  - class: org.jlab.ersap.actor.pcap.engine.PcapProcessorEngine
    name: Processor
configuration:
  io-services:
    reader:
      connections:
        - ip: "129.57.69.15"
          host: "localhost"
          port: 9000
        - ip: "129.57.69.14"
          host: "localhost"
          port: 9001
        - ip: "129.57.177.7"
          host: "localhost"
          port: 9002
        - ip: "129.57.69.12"
          host: "localhost"
          port: 9003
      ringBufferSize: 1024
      socketBufferSize: 1024
      connectionTimeout: 5000
      readTimeout: 2000
    writer:
      outputDir: "output"
  services:
    Processor:
mime-types:
  - binary/bytes
  - binary/data-jobj
  - text/plain 