---
io-services:
  reader:
    class: org.jlab.ersap.actor.pcap.engine.PcapSourceEngine
    name: Source
  writer:
    class: org.jlab.ersap.actor.pcap.engine.PcapSinkEngine
    name: Sink
services:
  - class: org.jlab.ersap.actor.pcap.engine.PcapProcessorEngine
    name: Processor
configuration:
  io-services:
    reader:
      streamHost: "localhost"
      streamPort: 9001
      ringBufferSize: 1024
      socketBufferSize: 16384
      connectionTimeout: 5000
      readTimeout: 2000
    writer:
      outputDir: "output"
  services:
    Processor:
mime-types:
  - binary/bytes
  - binary/data-jobj
  - text/plain 