chain:
  - type: cpu
    node: node1
    in_port: 55555
    out_port: 55556
    params:
      threads: 1
      latency: 100
      mem_footprint: 0.01
      output_size: 0.001
  - type: gpu
    node: node2
    in_port: 55556
    out_port: 55557
    params:
      matrix_width: 2048
      send_rate: 25
      group_size: 2048
  - type: cpu
    node: node3
    in_port: 55557
    out_port: 55558
    params:
      threads: 1
      latency: 100
      mem_footprint: 0.01
      output_size: 0.001 