# Needs further refinement
# Github README: https://github.com/ncabatoff/process-exporter

# DONOT comment at the end of the line!

process_names:
  - name: "{{.ExeBase}}"
    # Above "name" defines what will show in metrics 'namedprocess_namegroup_memory_bytes{groupname="xxx"}''
    comm:
      # Commands can be seen in the second field of /proc/<pid>/stat minus parens.
      # Trucated at 15 chars so "process-exporter" is trucated as "process-exporte".
      - iperf3
      - process-exporte
      - prometheus
