---
# Schema for CPU Emulator Workflow Configuration
workflow:
  name:
    type: string
    required: true
    description: "Name of the workflow"
  description:
    type: string
    required: false
    description: "Description of the workflow"

platform:
  name:
    type: string
    required: true
    description: "Platform name (e.g., jlab_slurm)"
  job_runner:
    type: string
    required: true
    description: "Job runner type (e.g., slurm)"

components:
  type: object
  required: true
  description: "Component instances in the workflow"
  patternProperties:
    "^[a-zA-Z][a-zA-Z0-9_]*$":  # Component ID pattern
      type: object
      required: ["type", "resources"]
      properties:
        type:
          type: string
          enum: ["receiver", "emulator", "sender"]
          description: "Type of the component"
        resources:
          type: object
          required: ["partition", "cpus_per_task", "mem"]
          properties:
            cpus_per_task:
              type: integer
              default: 4
            mem:
              type: string
            partition:
              type: string
        network:
          type: object
          required: ["port"]
          properties:
            port:
              type: integer
            bind_address:
              type: string
              default: "0.0.0.0"
        configuration:  # For emulator type
          type: object
          properties:
            threads:
              type: integer
              default: 4
            latency:
              type: integer
              default: 50
            mem_footprint:
              type: float
              default: 0.05
            output_size:
              type: float
              default: 0.001
        test_data:  # For sender type
          type: object
          properties:
            size:
              type: string
              default: "100M"

edges:
  type: array
  required: true
  description: "Relationships between components"
  items:
    type: object
    required: ["from", "to", "type"]
    properties:
      from:
        type: string
        description: "Source component ID"
      to:
        type: string
        description: "Target component ID"
      type:
        type: string
        enum: ["ready", "succeeded", "completed"]
        description: "Type of relationship"
      condition:
        type: string
        description: "Optional condition for the edge"

containers:
  image_path:
    type: string
    required: true
    description: "Path to the container image" 