components:
  emulator-1:
    configuration:
      latency: 50
      mem_footprint: 0.05
      output_size: 0.001
      threads: 4
    network:
      port: 50888
    resources:
      cpus_per_task: 4
      mem: 8G
      partition: ifarm
    type: emulator
  receiver-1:
    network:
      bind_address: 0.0.0.0
      port: 50080
    resources:
      cpus_per_task: 4
      mem: 8G
      partition: ifarm
    type: receiver
  sender-1:
    resources:
      cpus_per_task: 4
      mem: 8G
      partition: ifarm
    test_data:
      size: 100M
    type: sender
containers:
  image_path: cpu-emu.sif
edges:
- description: send
  from: sender-1
  to: emulator-1
- description: receive
  from: emulator-1
  to: receiver-1
platform:
  job_runner: slurm
  name: jlab_slurm
workflow:
  description: gui-3node-test
  name: gui-3node-test
