# Test configuration for multi-GPU proxy workflow with nodelist specification
workflow:
  name: multi-gpu-proxy-test
  description: Multi-GPU proxy workflow with explicit node assignment and component-specific parameters

platform:
  name: jlab_slurm

containers:
  image_path: gpu-proxy.sif

# Sender configuration with component-specific parameters
sender:
  target_port: 55555
  send_rate: 150
  group_size: 30720000
  send_all_ones: 0
  socket_hwm: 1

# Receiver configuration  
receiver:
  listen_port: 55560

# GPU Proxies with explicit node assignment and component-specific parameters
gpu_proxies:
  - device: "gpu"
    partition: gpu
    gpus: 1
    mem: 100G
    cpus: 4
    in_port: 55555
    out_port: 55556
    device_id: 0
    nic: eth1  # Optional: specify network interface for this proxy
    nodelist: "gpu-node-01"  # Explicit node assignment for first proxy
    # Component-specific processing parameters
    matrix_width: 1024  # Smaller matrix for first proxy
    proxy_rate: 0.8     # Slower processing rate
    socket_hwm: 2       # Higher socket buffer
    
  - device: "gpu"
    partition: gpu
    gpus: 1
    mem: 100G
    cpus: 4
    in_port: 55556
    out_port: 55557
    device_id: 1
    # nic: eth2  # Optional: if not specified, auto-detects default interface
    nodelist: "gpu-node-02"  # Explicit node assignment for second proxy
    # Component-specific processing parameters
    matrix_width: 4096  # Larger matrix for second proxy
    proxy_rate: 1.2     # Faster processing rate
    socket_hwm: 1       # Default socket buffer
    
  - device: "gpu"
    partition: gpu
    gpus: 1
    mem: 100G
    cpus: 4
    in_port: 55557
    out_port: 55558
    device_id: 2
    nic: eth3  # Optional: specify network interface for this proxy
    nodelist: "gpu-node-03"  # Explicit node assignment for third proxy
    # Component-specific processing parameters (uses defaults)
    # matrix_width: not specified - uses default (2048)
    # proxy_rate: not specified - uses default (1.0)
    # socket_hwm: not specified - uses default (1) 