# Configuration for CPU Emulator Workflow
---
workflow:
  name: "cpu-emu"
  description: "Cylc-based CPU Emulator Testing Workflow"

platform:
  name: "jlab_slurm"
  cylc_path: "/path/to/cylc-env/bin/"
  hosts: "tsai@ifarm2402"
  job_runner: "slurm"

resources:
  receiver:
    ntasks: 1
    cpus_per_task: 4
    mem: "8G" # slurm asks for 8G
    partition: "ifarm"
    timeout: "2h"
  emulator:
    ntasks: 1
    cpus_per_task: 4
    mem: "16G"
    partition: "ifarm"
    timeout: "2h"
  sender:
    ntasks: 1
    cpus_per_task: 4
    mem: "8G"
    partition: "ifarm"
    timeout: "2h"

network:
  receiver_port: 50080
  emulator_port: 50888

emulator:
  threads: 4
  latency: 50          # Processing latency per GB
  mem_footprint: 0.05  # Memory footprint in GB
  output_size: 0.001   # Output size in GB

test_data:
  size: "100M"        # Size of test data to send

containers:
  cpu_emulator:
    image: "cpu-emu.sif"
    docker_source: "jlabtsai/rtdp-cpu_emu:latest" 