latency: 50
mem_footprint: 0.05
network:
  listen_port: 50802
  target_ip: ${TARGET_IP}
  target_port: ${TARGET_PORT}
  verbosity: 1
output_dir: /output
output_size: 0.001
processing_type: cpu_intensive
threads: 8
