connections:
- buffer_size: 1M
  data_type: processed
  source: aggregator1
id: receiver1
network:
  bind_address: 0.0.0.0
  connect_to:
  - host: localhost
    port: 50803
  listen_port: 50804
receiver_config:
  buffer_size: 64M
  compression: false
  data_validation: true
  output_dir: received_data
resources:
  cpus_per_task: 4
  mem: 4G
  partition: ifarm
type: receiver
