---
io-services:
  reader:
    class: org.jlab.ersap.actor.sampa.SampaStreamReader
    name: sampa-reader
  writer:
    class: org.jlab.ersap.std.services.StreamWriter
    name: sampa-writer

services:
  - class: org.jlab.ersap.actor.sampa.SampaDecoder
    name: sampa-decoder
  - class: org.jlab.ersap.actor.sampa.SampaProcessor
    name: sampa-processor

configuration:
  io-services:
    reader:
      port: 5000
      host: localhost
      max-buffer-size: 65536
    writer:
      type: binary
      compression: gzip
      file-prefix: sampa_data_
      destination: ${ERSAP_USER_DATA}/data/output
      
  services:
    sampa-decoder:
      debug: false
    sampa-processor:
      debug: false

mime-types:
  - binary/data-sampa-stream
  - binary/data-sampa-decoded
  - binary/data-sampa-processed

container: sampa-container 