---
io-services:
  reader:
    class: org.jlab.ersap.actor.pcap.engine.Pcap2StreamSourceEngine
    name: pcap-source
  writer:
    class: org.jlab.epsci.ersap.std.services.StreamWriter
    name: StreamWriter

services:
  - class: org.jlab.ersap.actor.examples.EchoEngine
    name: Echo

configuration:
  io-services:
    reader:
      streamHost: localhost
      streamPort: 5000
      ringBufferSize: 1024
      connectionTimeout: 5000
      readTimeout: 10000
      byteOrder: BIG_ENDIAN
    writer:
      file_path: ${ERSAP_USER_DATA}/output/pcap_data.dat

---
io-services:
  reader:
    class: org.jlab.ersap.actor.pcap.engine.Pcap2StreamMultiSourceEngine
    name: pcap-multi-source
  writer:
    class: org.jlab.epsci.ersap.std.services.StreamWriter
    name: StreamWriter

services:
  - class: org.jlab.ersap.actor.examples.EchoEngine
    name: Echo

configuration:
  io-services:
    reader:
      ringBufferSize: 1024
      connectionTimeout: 5000
      readTimeout: 10000
      byteOrder: BIG_ENDIAN
      streams:
        - host: localhost
          port: 5000
        - host: localhost
          port: 5001
        - host: localhost
          port: 5002
    writer:
      file_path: ${ERSAP_USER_DATA}/output/pcap_multi_data.dat 