#!/bin/bash
#set -x
CHOME=
if [ -e $1.cc ]
then
    g++ -DNO_MAKEFILE -Wall -std=c++17 -O3 $1.cc -o $1 -lm -lpthread -lyaml > $1.out 2> $1.err
    less $1.err
    #vim $1.cc
#    if [ -e $1 ]
#    then
#        mv $1 ~/bin
#    fi
else
    echo "No such file $1.cc"
fi
# for f in *cc; do ./buildp $(basename $f .cc); done
