---
# ERSAP Services Configuration File
# This file defines the services, their connections, and configuration parameters

io-services:
  # Input/Output services for data ingestion and output
  reader:
    # The source engine that reads PCAP data from socket connections
    class: org.jlab.ersap.actor.pcap.engine.PcapSourceEngine  # Java class implementing the source engine
    name: Source  # Service name used for identification in the orchestrator
  writer:
    # The sink engine that writes processed data to output files
    class: org.jlab.ersap.actor.pcap.engine.PcapSinkEngine  # Java class implementing the sink engine
    name: Sink  # Service name used for identification in the orchestrator

services:
  # Processing services that transform data between source and sink
  - class: org.jlab.ersap.actor.pcap.engine.PcapProcessorEngine  # Java class implementing the processor engine
    name: Processor  # Service name used for identification in the orchestrator

configuration:
  io-services:
    reader:
      connections:
        # List of socket connections to read PCAP data from
        - ip: "129.57.69.15"  # IP address of the socket server
          host: "localhost"   # Host name (used for connection establishment)
          port: 9000          # Port number to connect to
        - ip: "129.57.69.14"  # IP address of the socket server
          host: "localhost"   # Host name (used for connection establishment)
          port: 9001          # Port number to connect to
        - ip: "129.57.177.7"  # IP address of the socket server
          host: "localhost"   # Host name (used for connection establishment)
          port: 9002          # Port number to connect to
        - ip: "129.57.69.12"  # IP address of the socket server
          host: "localhost"   # Host name (used for connection establishment)
          port: 9003          # Port number to connect to
      ringBufferSize: 1024     # Size of the internal ring buffer for packet processing (number of slots)
      socketBufferSize: 1024   # Size of the socket buffer in bytes for receiving packets
      connectionTimeout: 5000  # Timeout in milliseconds for establishing a connection
      readTimeout: 2000        # Timeout in milliseconds for reading data from the socket
    writer:
      outputDir: "output"      # Directory where processed packets will be written

  services:
    Processor:
      # Configuration parameters for the Processor service can be added here
      # For example: filter: "ip.src == 192.168.10.1" to filter packets by source IP

mime-types:
  # Supported MIME types for data exchange between services
  - binary/bytes     # Raw binary data
  - binary/data-jobj # Java serialized objects
  - text/plain       # Plain text data 